GET https://jsonplaceholder.typicode.com/posts

###
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "title": "foo",
    "body": "bar",
    "userId": 1
}


###
GET http://localhost:3000/articles


###
GET http://localhost:3000/articles/Jack Bauer

###
PUT http://localhost:3000/articles/Jack Bauer

###
GET http://localhost:3000/articles/Chucky Norris
